# Generated by Django 3.2.13 on 2022-05-17 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="Shipping address")),
                ("billing_address", models.TextField(verbose_name="Billing address")),
                (
                    "products_price",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                ("delivery_code", models.IntegerField()),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("pending", "pending"),
                            ("shipped", "shipped"),
                            ("delivered", "delivered"),
                        ],
                        default="pending",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShipmentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="Price per unit"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
