# Generated by Django 3.2.13 on 2022-05-18 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_price"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=8, max_digits=16, verbose_name="Price per unit"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=8, max_digits=16, verbose_name="Price"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="shipment",
            name="products_price",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.DeleteModel(
            name="ShipmentDetails",
        ),
        migrations.AddField(
            model_name="shipmentdetail",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shipments.shipment"
            ),
        ),
    ]
