# Generated by Django 3.2.13 on 2022-05-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_auto_20220518_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="reference_id",
            field=models.CharField(
                default="ABCDEF", max_length=20, verbose_name="Reference ID"
            ),
            preserve_default=False,
        ),
    ]
